### ISSUE TITLE
add error managment

### ISSUE THREAD

**Issue by tarekziade** [tarekziade/kinto-chrome#2]
something that looks like chrome.runtime.lastError 

https://developer.chrome.com/extensions/runtime#property-lastError

**Comment by michielbdejong** [comment]
Maybe https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/Extension/lastError is the thing to use for this.

**Comment by michielbdejong** [comment]
Actually, `chrome.runtime.lastError` / `extension.lastError` is only for quota errors. Should find a way to deal with sync errors.

**Comment by michielbdejong** [comment]
Will leave `extension.lastError` out of scope until we start enforcing quota. For now, just throwing errors when invalid config object is being set.
