### ISSUE TITLE
Rename this repo to storage-sync and publish to npm

### ISSUE THREAD

**Issue by michielbdejong** [tarekziade/kinto-chrome#36]
Hi! I would like to rename this repo to storage-sync, and publish the cross-browser shim to npm as 'storage-sync', for people to browserify it into their apps.

Consensus? @n1k0 @tarekziade @Natim @magopian @leplatrem

**Comment by n1k0** [comment]
+1
Le 29 mars 2016 5:05 AM, "Michiel de Jong" notifications@github.com a
écrit :

**Comment by leplatrem** [comment]
+1

**Comment by Natim** [comment]
+1

**Comment by michielbdejong** [comment]
OK, I guess that's enough concensus. :) We can always re-rename it if we come to a different insight later.
